sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  timeout: 720
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal test --only-dependencies
- stack --stack-yaml stack.ghc-8.2.yaml --no-terminal test --only-dependencies
- stack --stack-yaml stack.ghc-8.0.yaml --no-terminal test --only-dependencies
jobs:
  include:
    - stage: Run stack build pixela
      script: stack --no-terminal build pixela --fast
    - stage: Run stack build pixela-cli
      script: stack --no-terminal build pixela-cli --fast
    - stage: Run stack build pixela --pedantic
      script:
      - stack clean
      - stack --no-terminal build pixela --fast --pedantic
    - stage: Run stack build pixela-cli --pedantic
      script:
      - stack clean
      - stack --no-terminal build pixela-cli --fast --pedantic
    - stage: Run HLint
      script: curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
    - stage: Run stack --stack-yaml stack.ghc-8.2.yaml build pixela
      script:
      - stack clean
      - stack --stack-yaml stack.ghc-8.2.yaml --no-terminal build pixela --fast
    - stage: Run stack --stack-yaml stack.ghc-8.2.yaml build pixela-cli
      script:
      - stack clean
      - stack --stack-yaml stack.ghc-8.2.yaml --no-terminal build pixela-cli --fast
    - stage: Run stack --stack-yaml stack.ghc-8.0.yaml build pixela
      script:
      - stack clean
      - stack --stack-yaml stack.ghc-8.0.yaml --no-terminal build pixela --fast
    - stage: Run stack --stack-yaml stack.ghc-8.0.yaml build pixela-cli
      script:
      - stack clean
      - stack --stack-yaml stack.ghc-8.0.yaml --no-terminal build pixela-cli --fast

notifications:
  email: false
